### ISSUE TITLE
Will not direct play on ATV4.

### ISSUE THREAD

**Issue by jocoman** [plexinc-plugins/ABC.bundle#16]
I also posted this in the Services.bundle plugin comments.  With direct play enabled ABC is the only channel of the major broadcast channels that I use (CBS, NBC, FOX, CW) that will not play content.  The channel launches and I can view and select content.  However, when launched the ring spins a couple of times and then goes back to the content list without playing.  This does not happen on the Roku client.  Direct play works fine there.  ABC on ATV4 will play if direct play is disabled but the video quality suffers.  This either has to be a specific ATV4 client issue, or there is some broken code in the channel or the services.bundle file.  Will you please investigate this issue?  Thanks.

**Comment by sander1** [comment]
Duplicate: https://github.com/plexinc-plugins/Services.bundle/issues/885
