### ISSUE TITLE
Content Unavailable

### ISSUE THREAD

**Issue by TragicWarrior** [plexinc-plugins/ABC.bundle#22]
Trying to launch the channel, on the Roku App I get the error message:

Content Unavailable
Sorry, we couldn't load the requested content

on the Web Interface I get:

The channel is not responding

We use this channel once a week and it was working last week.  I was on Plex 1.1.4 but tried upgrading to the latest version just now to fix the issue...it did not help.  I still get these error messages.

**Comment by sander1** [comment]
The channel works as expected on my test/dev system. I need some log files to see what's going on on your system (`com.plexapp.plugins.abc.log`).

How to find log files: https://support.plex.tv/hc/en-us/articles/201106148-Channel-Log-Files

**Comment by TragicWarrior** [comment]
It's working now.  I'm going to explain it away by the massive Amazon outage yesterday.

**Comment by sander1** [comment]
Is your server running on Windows by any chance? If so, this could have been an issue: https://github.com/plexinc-plugins/ABC.bundle/commit/558be932aa69ead4fdbe50311863277d916cd1a2
