### ISSUE TITLE
Episode playback fails on TiVo Hydra client

### ISSUE THREAD

**Issue by tomtj7964** [plexinc-plugins/ABC.bundle#23]
Hello,
    I don't know if I'm reporting this right but I will try.  Please advise with any feedback or suggestions.  So I am having trouble playing ABC episodes from my TiVo plex Clent.  The Tivo is at 21.7.2.RC19-846-6-846, (known as Hydra - Tivo Experience as well I believe)  When I try to playback videos on the TiVo it presents three dots and then changes to a screen which displays, (There was a problem this item. The video did not start playing at this time.)  I believe the issue began when I upgraded the TiVo to the TiVo Hydra client.  For reference, I have uninstalled and re-installed the ABC plugin on my Win 10 Plex Media Server.  I also pulled the latest github files for the ABC bundle.  The episodes play fine when I play directly on my WIN 10 Plex Media Server.  If it's useful I can be reached at promiseland.tony@att.net  I am attaching some log files that seem relevant, please advise as required and Thanks for any assistance you may provide.
TT

[com.plexapp.system.log](https://github.com/plexinc-plugins/ABC.bundle/files/1962788/com.plexapp.system.log)
[com.plexapp.plugins.abc.log](https://github.com/plexinc-plugins/ABC.bundle/files/1962789/com.plexapp.plugins.abc.log)

**Comment by tomtj7964** [comment]
I'm attaching a couple of cleaner log files.  Note,  the errors to the TJT.bundle are not in this call.

[com.plexapp.plugins.abc.log](https://github.com/plexinc-plugins/ABC.bundle/files/1962816/com.plexapp.plugins.abc.log)
[com.plexapp.system.log](https://github.com/plexinc-plugins/ABC.bundle/files/1962817/com.plexapp.system.log)

**Comment by sander1** [comment]
I'm sorry to say, but if the plugin works on at least 1 Plex player, the issue is not with the channel but with the other player, in this case the TiVo. Unfortunately there is nothing to fix in the plugin code, the log files show no errors.

I'm not familiar with TiVos or the Plex for TiVo client. I think this is the best forum part where you can bring up the issue: https://forums.plex.tv/categories/smart-tvs

**Comment by tomtj7964** [comment]
Sander,

     Thanks so much for the quick and expert review.  I will follow your suggestion and hope they will be helpful like you.  Take Care ... Tony
